$terminal = uwsm app -- xdg-terminal-exec
$terminal-alt = uwsm app -- foot
$browser = hyprkarl-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(hyprkarl-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Foot, exec, $terminal-alt
bindd = SUPER SHIFT, F, File manager, exec, hyprkarl-launch-tui yazi
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, E, Editor, exec, hyprkarl-launch-editor
bindd = SUPER SHIFT, O, Obsidian, exec, hyprkarl-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, V, Vesktop, exec, hyprkarl-launch-or-focus vesktop "uwsm app -- vesktop"

bindd = SUPER SHIFT, D, Dictionary, exec, $terminal --app-id=TUI.float -e hyprkarl-dictionary