# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume,  Volume up,                exec, hk-volume raise
bindeld = ,XF86AudioLowerVolume,  Volume down,              exec, hk-volume lower
bindeld = ,XF86AudioMute,         Mute,                     exec, hk-volume toggle
bindeld = ,XF86AudioMicMute,      Mute microphone,          exec, hk-mic toggle
bindeld = ,XF86MonBrightnessUp,   Brightness up,            exec, hk-brightness-display +5%
bindeld = ,XF86MonBrightnessDown, Brightness down,          exec, hk-brightness-display 5%-
bindeld = ,XF86KbdBrightnessUp,   Keyboard brightness up,   exec, hk-brightness-keyboard up
bindeld = ,XF86KbdBrightnessDown, Keyboard brightness down, exec, hk-brightness-keyboard down

# Playerctl
bindld = , XF86AudioNext,  Next track,     exec, hk-playerctl next
bindld = , XF86AudioPause, Pause,          exec, hk-playerctl play-pause
bindld = , XF86AudioPlay,  Play,           exec, hk-playerctl play-pause
bindld = , XF86AudioPrev,  Previous track, exec, hk-playerctl previous

# Switch audio output with Super + Mute
bindld = SUPER, XF86AudioMute, Switch audio output, exec, hk-audio-switch
