# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume,  Volume up,                exec, hyprkarl-volume raise
bindeld = ,XF86AudioLowerVolume,  Volume down,              exec, hyprkarl-volume lower
bindeld = ,XF86AudioMute,         Mute,                     exec, hyprkarl-volume toggle
bindeld = ,XF86AudioMicMute,      Mute microphone,          exec, hyprkarl-mic toggle
bindeld = ,XF86MonBrightnessUp,   Brightness up,            exec, hyprkarl-brightness-display +5%
bindeld = ,XF86MonBrightnessDown, Brightness down,          exec, hyprkarl-brightness-display 5%-
bindeld = ,XF86KbdBrightnessUp,   Keyboard brightness up,   exec, hyprkarl-brightness-keyboard up
bindeld = ,XF86KbdBrightnessDown, Keyboard brightness down, exec, hyprkarl-brightness-keyboard down

# Playerctl
bindld = , XF86AudioNext,  Next track,     exec, hyprkarl-playerctl next
bindld = , XF86AudioPause, Pause,          exec, hyprkarl-playerctl play-pause
bindld = , XF86AudioPlay,  Play,           exec, hyprkarl-playerctl play-pause
bindld = , XF86AudioPrev,  Previous track, exec, hyprkarl-playerctl previous

# Switch audio output with Super + Mute
bindld = SUPER, XF86AudioMute, Switch audio output, exec, hyprkarl-audio-switch
