foreground              #D5D5D5
background              #1a1616
selection_foreground    #1a1616
selection_background    #D5D5D5
cursor                  #63005A
cursor_text_color       #D5D5D5

active_tab_foreground     #1a1616
active_tab_background     #63005A
inactive_tab_foreground   #D5D5D5
inactive_tab_background   #262121

# black
color0      #2a2020
color8      #3d3030

# red
color1      #cc5555
color9      #dd6666

# green
color2      #a07a98
color10     #c09ab8

# yellow
color3      #c084b8
color11     #f2a7e8

# blue
color4      #6644aa
color12     #8866cc

# magenta
color5      #63005A
color13     #8a1a80

# cyan
color6      #9966cc
color14     #bb88ee

# white
color7      #D5D5D5
color15     #e8e8e8