exec-once = systemctl --user start hypridle.service
exec-once = uwsm-app -- mako
exec-once = uwsm app -- systemctl --user start hyprpolkitagent
exec-once = uwsm app -- ags run
exec-once = uwsm app -- hyprpaper
exec-once = hk-wallpaper init || hk-wallpaper cycle

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
