source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/apps.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hyprkarl/current/theme/hyprland.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# This is to combat a bug with MS Edge creating tooltips as windows that hyprland tries to tile.
# I'll probably remove it from the github repo at some point, because most people don't use Edge.
windowrule = float on, no_focus on, pin on, keep_aspect_ratio on, border_size 0, center off, move min(cursor_x\,monitor_w-window_w) min(cursor_y+20\,monitor_h-window_h), match:class ^()$,match:title ^()$,match:initial_class ^()$,match:initial_title ^()$