source = ~/.config/hyprkarl/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/hyprkarl/current/wallpaper
    blur_passes = 2
}

animations {
    enabled = false
}

# Password input field
input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = JetBrainsMono Nerd Font Propo
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>Authentication Failed ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 2
    fade_on_empty = false
}

# Clock
label {
    monitor = 
    text = $TIME12
    position = 0, -200
    valign = top

    color = $font_color
    font_family = JetBrainsMono Nerd Font Propo Bold
    font_size = 64

    shadow_passes = 2
}

# Fingerprint scanning
label {
    monitor = 
    text = cmd[update:200] [[ "$FPRINTPROMPT" == "Could not match fingerprint. Try again." ]] && echo "[]" || echo "$FPRINTPROMPT"
    position = 0, -100

    color = $font_color
    font_family = JetBrainsMono Nerd Font Propo
    font_size = 32

    shadow_passes = 2
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = 󰈷
    fingerprint:present_message = [󰈷]
    fingerprint:retry_delay = 400
}
