$color = {{rgba(base.background,0.95)}}
$inner_color = {{rgba(base.background,0.65)}}
$outer_color = {{rgba(accent.primary.base,0.9)}}

$font_color = {{rgba(ui.text_secondary,1)}}
$check_color = {{rgba(accent.secondary.base,1)}}
