foreground              {{base.foreground}}
background              {{base.background}}
selection_foreground    {{ui.selection_fg}}
selection_background    {{ui.selection_bg}}
cursor                  {{ui.cursor}}
cursor_text_color       {{base.background}}

active_tab_foreground   {{base.background}}
active_tab_background   {{ansi.magenta}}
inactive_tab_foreground {{base.foreground}}
inactive_tab_background {{ui.panel}}

# black
color0 {{ansi.black}}
color8 {{bright.black}}

# red
color1 {{ansi.red}}
color9 {{bright.red}}

# green
color2 {{ansi.green}}
color10 {{bright.green}}

# yellow
color3 {{ansi.yellow}}
color11 {{bright.yellow}}

# blue
color4 {{ansi.blue}}
color12 {{bright.blue}}

# magenta
color5 {{ansi.magenta}}
color13 {{bright.magenta}}

# cyan
color6 {{ansi.cyan}}
color14 {{bright.cyan}}

# white
color7 {{ansi.white}}
color15 {{bright.white}}