Primary = "#A7C080"
Subtle = "#527974"
Success = "#A7C080"
Error = "#E67E80"

Normal = "#D3C6AA"
Disabled = "#868D80"
Border = "#56635F"

SignalHigh = ["#83C092", "#83C092"]
SignalLow = ["#343F44", "#343F44"]

Saved = "#83C092"

TitleIcon = "󰖩 "
NetworkSecureIcon = "󰌾 "
NetworkOpenIcon = "󰿆 "
NetworkUnknownIcon = " "
NetworkSavedIcon = " "