[[opener.open-with]]
run    = "$HYPRKARL_PATH/bin/hyprkarl-open-with %s1"
for    = "linux"
orphan = true
desc   = "Open with..."

[[opener.set-wallpaper]]
run  = "hyprkarl-wallpaper-add %s1"
for  = "linux"
desc = "Set as wallpaper"

[[open.prepend_rules]]
mime = "image/*"
use  = [ "open", "open-with", "reveal", "set-wallpaper" ]

[[open.append_rules]]
url = "*"
use = [ "open", "open-with" ]
