[colors]

[colors.primary]
background = '#1a1616'
foreground = '#D5D5D5'

[colors.selection]
text = '#1a1616'
background = '#D5D5D5'

[colors.cursor]
text = '#D5D5D5'
cursor = '#63005A'

[colors.normal]
black =   '#2a2020'
red =     '#cc5555'
green =   '#a07a98'
yellow =  '#c084b8'
blue =    '#6644aa'
magenta = '#63005A'
cyan =    '#9966cc'
white =   '#D5D5D5'

[colors.bright]
black =   '#3d3030'
red =     '#dd6666'
green =   '#c09ab8'
yellow =  '#f2a7e8'
blue =    '#8866cc'
magenta = '#8a1a80'
cyan =    '#bb88ee'
white =   '#e8e8e8'